steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'soccer-translation', '--trigger-http', '--runtime=${_RUNTIME}', '--source=${_SOURCE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'add-iam-policy-binding', 'soccer-translation', '--member=allUsers', '--role=${_ROLE}']

substitutions:
  _SOURCE: 'https://source.developers.google.com/projects/nih-nci-dceg-connect-prod-6d04/repos/github_episphere_soccer-translation/moveable-aliases/prod'
  _RUNTIME: 'nodejs20'
  _ROLE: 'roles/cloudfunctions.invoker'