steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'deploy',
    '${_SERVICE}',
    '--region=${_REGION}',
    '--source=${_SOURCE}',
    '--function=${_FUNCTION}',
    '--base-image=${_BASE_IMAGE}',
    '--timeout=${_TIMEOUT}',
  ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'services',
    'add-iam-policy-binding',
    '${_SERVICE}',
    '--region=${_REGION}',
    '--member=${_MEMBER}',
    '--role=${_ROLE}'
  ]

substitutions:
  _BASE_IMAGE: us-central1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/nodejs20
  _FUNCTION: connect-soccer
  _MEMBER: allUsers
  _REGION: us-central1
  _ROLE: roles/run.invoker
  _SERVICE: connect-soccer
  _SOURCE: .
  _TIMEOUT: 120s  